# Generated by Django 3.2.7 on 2021-09-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0002_auto_20210922_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='City',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Province',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='State',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Street',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
