# Generated by Django 3.2.7 on 2021-10-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wrapper', '0006_auto_20211018_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardview',
            options={'ordering': ['Date_Created']},
        ),
    ]
