# Generated by Django 3.2.7 on 2021-10-18 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wrapper', '0005_profile_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboardview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, null=True)),
                ('bi_software', models.CharField(max_length=200, null=True)),
                ('dashboard_title', models.CharField(max_length=200, null=True)),
                ('icon_pic', models.ImageField(blank=True, default='Metrocom.png', null=True, upload_to='')),
                ('link_iframe', models.CharField(max_length=200, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Profile_pic',
            field=models.ImageField(blank=True, default='Metrocom.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
